[auth]
enabled = true
site_url = "http://localhost:3000"  # Ubah dari http://127.0.0.1:3000
additional_redirect_urls = []       # Ubah dari ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true         # Ubah dari false
secure_password_change = false
max_frequency = "1m0s"             # Ubah dari "1s"
otp_length = 6
otp_expiry = 3600